/**
 * Generated by orval v6.3.0 🍺
 * Do not edit manually.
 * Drop API
 * The OpenAPI schema for drop.energy
 * OpenAPI spec version: 0.1.0
 */
import { useQuery, UseQueryOptions, QueryFunction } from "react-query";
import type { HTTPValidationError } from ".././model";
import { customInstance } from ".././axios";

type AsyncReturnType<T extends (...args: any) => Promise<any>> = T extends (
  ...args: any
) => Promise<infer R>
  ? R
  : any;

/**
 * @summary Get User Weekly Trend
 */
export const getUserWeeklyTrendKpisWeeklyChangeApartmentIdGet = (
  apartmentid: number
) => {
  return customInstance<number>({
    url: `/kpis/weekly-change/${apartmentid}`,
    method: "get",
  });
};

export const getGetUserWeeklyTrendKpisWeeklyChangeApartmentIdGetQueryKey = (
  apartmentid: number
) => [`/kpis/weekly-change/${apartmentid}`];

export const useGetUserWeeklyTrendKpisWeeklyChangeApartmentIdGet = <
  TData = AsyncReturnType<
    typeof getUserWeeklyTrendKpisWeeklyChangeApartmentIdGet
  >,
  TError = HTTPValidationError
>(
  apartmentid: number,
  options?: {
    query?: UseQueryOptions<
      AsyncReturnType<typeof getUserWeeklyTrendKpisWeeklyChangeApartmentIdGet>,
      TError,
      TData
    >;
  }
) => {
  const { query: queryOptions } = options || {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetUserWeeklyTrendKpisWeeklyChangeApartmentIdGetQueryKey(apartmentid);

  const queryFn: QueryFunction<
    AsyncReturnType<typeof getUserWeeklyTrendKpisWeeklyChangeApartmentIdGet>
  > = () => getUserWeeklyTrendKpisWeeklyChangeApartmentIdGet(apartmentid);

  const query = useQuery<
    AsyncReturnType<typeof getUserWeeklyTrendKpisWeeklyChangeApartmentIdGet>,
    TError,
    TData
  >(queryKey, queryFn, { enabled: !!apartmentid, ...queryOptions });

  return {
    queryKey,
    ...query,
  };
};

/**
 * @summary Hygiene Scores
 */
export const hygieneScoresHygieneScoresGroupIdDateGet = (
  groupid: number,
  date: string
) => {
  return customInstance<unknown>({
    url: `/hygiene-scores/${groupid}/${date}`,
    method: "get",
  });
};

export const getHygieneScoresHygieneScoresGroupIdDateGetQueryKey = (
  groupid: number,
  date: string
) => [`/hygiene-scores/${groupid}/${date}`];

export const useHygieneScoresHygieneScoresGroupIdDateGet = <
  TData = AsyncReturnType<typeof hygieneScoresHygieneScoresGroupIdDateGet>,
  TError = HTTPValidationError
>(
  groupid: number,
  date: string,
  options?: {
    query?: UseQueryOptions<
      AsyncReturnType<typeof hygieneScoresHygieneScoresGroupIdDateGet>,
      TError,
      TData
    >;
  }
) => {
  const { query: queryOptions } = options || {};

  const queryKey =
    queryOptions?.queryKey ??
    getHygieneScoresHygieneScoresGroupIdDateGetQueryKey(groupid, date);

  const queryFn: QueryFunction<
    AsyncReturnType<typeof hygieneScoresHygieneScoresGroupIdDateGet>
  > = () => hygieneScoresHygieneScoresGroupIdDateGet(groupid, date);

  const query = useQuery<
    AsyncReturnType<typeof hygieneScoresHygieneScoresGroupIdDateGet>,
    TError,
    TData
  >(queryKey, queryFn, { enabled: !!(groupid && date), ...queryOptions });

  return {
    queryKey,
    ...query,
  };
};

/**
 * @summary Sustainability Scores
 */
export const sustainabilityScoresSustainabilityScoresGroupIdDateGet = (
  groupid: number,
  date: string
) => {
  return customInstance<unknown>({
    url: `/sustainability-scores/${groupid}/${date}`,
    method: "get",
  });
};

export const getSustainabilityScoresSustainabilityScoresGroupIdDateGetQueryKey =
  (groupid: number, date: string) => [
    `/sustainability-scores/${groupid}/${date}`,
  ];

export const useSustainabilityScoresSustainabilityScoresGroupIdDateGet = <
  TData = AsyncReturnType<
    typeof sustainabilityScoresSustainabilityScoresGroupIdDateGet
  >,
  TError = HTTPValidationError
>(
  groupid: number,
  date: string,
  options?: {
    query?: UseQueryOptions<
      AsyncReturnType<
        typeof sustainabilityScoresSustainabilityScoresGroupIdDateGet
      >,
      TError,
      TData
    >;
  }
) => {
  const { query: queryOptions } = options || {};

  const queryKey =
    queryOptions?.queryKey ??
    getSustainabilityScoresSustainabilityScoresGroupIdDateGetQueryKey(
      groupid,
      date
    );

  const queryFn: QueryFunction<
    AsyncReturnType<
      typeof sustainabilityScoresSustainabilityScoresGroupIdDateGet
    >
  > = () =>
    sustainabilityScoresSustainabilityScoresGroupIdDateGet(groupid, date);

  const query = useQuery<
    AsyncReturnType<
      typeof sustainabilityScoresSustainabilityScoresGroupIdDateGet
    >,
    TError,
    TData
  >(queryKey, queryFn, { enabled: !!(groupid && date), ...queryOptions });

  return {
    queryKey,
    ...query,
  };
};
