import React from "react";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import { Sidebar } from "./Sidebar";
import styled from "styled-components";

const LayoutWrapper = styled.div`
  display: grid;

  grid-template-areas: "sidebar main";
  grid-template-columns: auto 1fr;

  height: 100vh;
  width: 100vw;
`;

export const Layout: React.FC = ({ children }) => (
  <LayoutWrapper>
    <Head>
      <title>DROP</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <Sidebar>
      <Image src="/logo.svg" height={100} width={200} alt="" />

      <LinkList>
        <LinkWrapper>
          <Link href="/apartments">Apartments</Link>
        </LinkWrapper>
        <LinkWrapper>
          <Link href="/users">Users</Link>
        </LinkWrapper>
        <LinkWrapper>
          <Link href="/settings">Settings</Link>
        </LinkWrapper>
      </LinkList>
    </Sidebar>

    {children}
  </LayoutWrapper>
);

const LinkWrapper = styled.li`
  cursor: pointer;
  font-family: NATS;
  color: ${(p) => p.theme.colors.primaryDark};

  font-size: ${(p) => p.theme.spacing.medium};
`;

const LinkList = styled.ul`
  display: flex;
  flex-direction: column;
  gap: ${(p) => p.theme.spacing.medium};
  padding-top: ${(p) => p.theme.spacing.xxlarge};
`;
