/**
 * Generated by orval v6.3.0 🍺
 * Do not edit manually.
 * Drop API
 * The OpenAPI schema for drop.energy
 * OpenAPI spec version: 0.1.0
 */
import { useQuery, UseQueryOptions, QueryFunction } from "react-query";
import { customInstance } from ".././axios";

type AsyncReturnType<T extends (...args: any) => Promise<any>> = T extends (
  ...args: any
) => Promise<infer R>
  ? R
  : any;

/**
 * @summary Index
 */
export const indexGet = () => {
  return customInstance<unknown>({ url: ``, method: "get" });
};

export const getIndexGetQueryKey = () => [``];

export const useIndexGet = <
  TData = AsyncReturnType<typeof indexGet>,
  TError = unknown
>(options?: {
  query?: UseQueryOptions<AsyncReturnType<typeof indexGet>, TError, TData>;
}) => {
  const { query: queryOptions } = options || {};

  const queryKey = queryOptions?.queryKey ?? getIndexGetQueryKey();

  const queryFn: QueryFunction<AsyncReturnType<typeof indexGet>> = () =>
    indexGet();

  const query = useQuery<AsyncReturnType<typeof indexGet>, TError, TData>(
    queryKey,
    queryFn,
    queryOptions
  );

  return {
    queryKey,
    ...query,
  };
};
