services:
    admin:
        build:
            context: admin
            target: development
        container_name: drop_admin
        ports:
            - 3000:3000
        env_file: .env

    api:
        build:
            context: backend
        container_name: drop_api
        ports:
            - 8000:8000
        env_file: backend/.env

    db:
        image: postgres
        container_name: db
        restart: always
        ports:
            - 6432:5432
        env_file:
            - backend/.env
