import type { NextPage } from "next";
import Head from "next/head";
import styled from "styled-components";
import { Layout } from "../components/Layout";
import { Main } from "../components/Main";
import { Sidebar } from "../components/Sidebar";

const Home: NextPage = () => {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Sidebar>
        <p>nice man</p>
      </Sidebar>

      <Main>
        <Title>sup bois</Title>
      </Main>
    </Layout>
  );
};

const Title = styled.h1`
  font-size: 3rem;
`;

export default Home;
