/**
 * Generated by orval v6.3.0 🍺
 * Do not edit manually.
 * Drop API
 * The OpenAPI schema for drop.energy
 * OpenAPI spec version: 0.1.0
 */

export interface ApplianceOptional {
  id?: number;
  measurement?: number | null;
  name?: string;
}
