/**
 * Generated by orval v6.3.0 🍺
 * Do not edit manually.
 * Drop API
 * The OpenAPI schema for drop.energy
 * OpenAPI spec version: 0.1.0
 */

export interface BaseUserPydantic {
  username?: string;
  password?: string;
  first_name?: string | null;
  last_name?: string | null;
  email?: string;
  active?: boolean;
  admin?: boolean;
  superuser?: boolean;
  last_login?: string | null;
}
