/**
 * Generated by orval v6.3.0 🍺
 * Do not edit manually.
 * Drop API
 * The OpenAPI schema for drop.energy
 * OpenAPI spec version: 0.1.0
 */

export interface ApartmentGroupsItem {
  apartment?: number | null;
  group_id?: number | null;
  id?: number;
}
