/**
 * Generated by orval v6.3.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface ApartmentItem {
    address?: string;
    appliance?: number | null;
    created_on?: string;
    id?: number;
    owner?: string;
    people?: number;
}
