/**
 * Generated by orval v6.3.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ApplianceItem } from "./applianceItem";

export interface AppliancePlural {
    rows?: ApplianceItem[];
}
