/**
 * Generated by orval v6.3.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type CountApartmentCountGetParams = {
    id?: number;
    id__operator?: unknown;
    address?: string;
    owner?: string;
    owner__match?: unknown;
    people?: number;
    people__operator?: unknown;
    created_on?: string;
    appliance?: number;
    appliance__operator?: unknown;
};
