/**
 * Generated by orval v6.3.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type CountGroupCountGetParams = {
    id?: number;
    id__operator?: unknown;
    name?: string;
    resident?: number;
    resident__operator?: unknown;
    apartment?: number;
    apartment__operator?: unknown;
};
