/**
 * Generated by orval v6.3.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type CountMeasurementCountGetParams = {
    id?: number;
    id__operator?: unknown;
    timestamp?: string;
    water_consumption?: number;
    power_consumption?: number;
};
