/**
 * Generated by orval v6.3.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type GetMeasurementGetParams = {
    id?: number;
    id__operator?: unknown;
    timestamp?: string;
    water_consumption?: number;
    power_consumption?: number;
    __order?: string;
    __page_size?: number;
    __page?: number;
    __visible_fields?: string;
};
