/**
 * Generated by orval v6.3.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type GetResidentGetParams = {
    id?: number;
    id__operator?: unknown;
    apartment?: number;
    apartment__operator?: unknown;
    __order?: string;
    __page_size?: number;
    __page?: number;
    __visible_fields?: string;
};
