/**
 * Generated by orval v6.3.0 🍺
 * Do not edit manually.
 * Drop API
 * The OpenAPI schema for drop.energy
 * OpenAPI spec version: 0.1.0
 */

export interface MeasurementIn {
  apartment?: number | null;
  appliance?: string;
  flow_time?: number;
  power_consumption?: number;
  temp?: number;
  timestamp?: string;
  water_consumption?: number;
}
