/**
 * Generated by orval v6.3.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface MeasurementOutput {
    id?: number;
    power_consumption?: number;
    timestamp?: string;
    water_consumption?: number;
}
