/**
 * Generated by orval v6.3.0 🍺
 * Do not edit manually.
 * Drop API
 * The OpenAPI schema for drop.energy
 * OpenAPI spec version: 0.1.0
 */
import { useQuery, UseQueryOptions, QueryFunction } from "react-query";
import type {
  DailyConsumptionResponse,
  HTTPValidationError,
  ConsumptionLastTwoWeeksResponse,
} from ".././model";
import { customInstance } from ".././axios";

type AsyncReturnType<T extends (...args: any) => Promise<any>> = T extends (
  ...args: any
) => Promise<infer R>
  ? R
  : any;

/**
 * @summary Get Consumption
 */
export const getConsumptionKpiConsumptionDailyApartmentIdDateGet = (
  apartmentid: number,
  date: string
) => {
  return customInstance<DailyConsumptionResponse>({
    url: `/kpi/consumption-daily/${apartmentid}/${date}`,
    method: "get",
  });
};

export const getGetConsumptionKpiConsumptionDailyApartmentIdDateGetQueryKey = (
  apartmentid: number,
  date: string
) => [`/kpi/consumption-daily/${apartmentid}/${date}`];

export const useGetConsumptionKpiConsumptionDailyApartmentIdDateGet = <
  TData = AsyncReturnType<
    typeof getConsumptionKpiConsumptionDailyApartmentIdDateGet
  >,
  TError = HTTPValidationError
>(
  apartmentid: number,
  date: string,
  options?: {
    query?: UseQueryOptions<
      AsyncReturnType<
        typeof getConsumptionKpiConsumptionDailyApartmentIdDateGet
      >,
      TError,
      TData
    >;
  }
) => {
  const { query: queryOptions } = options || {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetConsumptionKpiConsumptionDailyApartmentIdDateGetQueryKey(
      apartmentid,
      date
    );

  const queryFn: QueryFunction<
    AsyncReturnType<typeof getConsumptionKpiConsumptionDailyApartmentIdDateGet>
  > = () =>
    getConsumptionKpiConsumptionDailyApartmentIdDateGet(apartmentid, date);

  const query = useQuery<
    AsyncReturnType<typeof getConsumptionKpiConsumptionDailyApartmentIdDateGet>,
    TError,
    TData
  >(queryKey, queryFn, { enabled: !!(apartmentid && date), ...queryOptions });

  return {
    queryKey,
    ...query,
  };
};

/**
 * @summary Get Consumption Last Two Week
 */
export const getConsumptionLastTwoWeekKpiConsumptionWeeklyApartmentIdNumWeeksGet =
  (apartmentid: number, numweeks: number) => {
    return customInstance<ConsumptionLastTwoWeeksResponse[]>({
      url: `/kpi/consumption-weekly/${apartmentid}/${numweeks}`,
      method: "get",
    });
  };

export const getGetConsumptionLastTwoWeekKpiConsumptionWeeklyApartmentIdNumWeeksGetQueryKey =
  (apartmentid: number, numweeks: number) => [
    `/kpi/consumption-weekly/${apartmentid}/${numweeks}`,
  ];

export const useGetConsumptionLastTwoWeekKpiConsumptionWeeklyApartmentIdNumWeeksGet =
  <
    TData = AsyncReturnType<
      typeof getConsumptionLastTwoWeekKpiConsumptionWeeklyApartmentIdNumWeeksGet
    >,
    TError = HTTPValidationError
  >(
    apartmentid: number,
    numweeks: number,
    options?: {
      query?: UseQueryOptions<
        AsyncReturnType<
          typeof getConsumptionLastTwoWeekKpiConsumptionWeeklyApartmentIdNumWeeksGet
        >,
        TError,
        TData
      >;
    }
  ) => {
    const { query: queryOptions } = options || {};

    const queryKey =
      queryOptions?.queryKey ??
      getGetConsumptionLastTwoWeekKpiConsumptionWeeklyApartmentIdNumWeeksGetQueryKey(
        apartmentid,
        numweeks
      );

    const queryFn: QueryFunction<
      AsyncReturnType<
        typeof getConsumptionLastTwoWeekKpiConsumptionWeeklyApartmentIdNumWeeksGet
      >
    > = () =>
      getConsumptionLastTwoWeekKpiConsumptionWeeklyApartmentIdNumWeeksGet(
        apartmentid,
        numweeks
      );

    const query = useQuery<
      AsyncReturnType<
        typeof getConsumptionLastTwoWeekKpiConsumptionWeeklyApartmentIdNumWeeksGet
      >,
      TError,
      TData
    >(queryKey, queryFn, {
      enabled: !!(apartmentid && numweeks),
      ...queryOptions,
    });

    return {
      queryKey,
      ...query,
    };
  };
