/**
 * Generated by orval v6.3.0 🍺
 * Do not edit manually.
 * Drop API
 * The OpenAPI schema for drop.energy
 * OpenAPI spec version: 0.1.0
 */
import { useQuery, UseQueryOptions, QueryFunction } from "react-query";
import type {
  GroupPydantic,
  HTTPValidationError,
  ReadUsersUserGroupsApartmentIdGetParams,
} from ".././model";
import { customInstance } from ".././axios";

type AsyncReturnType<T extends (...args: any) => Promise<any>> = T extends (
  ...args: any
) => Promise<infer R>
  ? R
  : any;

/**
 * @summary Read Users
 */
export const readUsersUserGroupsApartmentIdGet = (
  apartmentid: number,
  params?: ReadUsersUserGroupsApartmentIdGetParams
) => {
  return customInstance<GroupPydantic[]>({
    url: `/user/groups/${apartmentid}`,
    method: "get",
    params,
  });
};

export const getReadUsersUserGroupsApartmentIdGetQueryKey = (
  apartmentid: number,
  params?: ReadUsersUserGroupsApartmentIdGetParams
) => [`/user/groups/${apartmentid}`, ...(params ? [params] : [])];

export const useReadUsersUserGroupsApartmentIdGet = <
  TData = AsyncReturnType<typeof readUsersUserGroupsApartmentIdGet>,
  TError = HTTPValidationError
>(
  apartmentid: number,
  params?: ReadUsersUserGroupsApartmentIdGetParams,
  options?: {
    query?: UseQueryOptions<
      AsyncReturnType<typeof readUsersUserGroupsApartmentIdGet>,
      TError,
      TData
    >;
  }
) => {
  const { query: queryOptions } = options || {};

  const queryKey =
    queryOptions?.queryKey ??
    getReadUsersUserGroupsApartmentIdGetQueryKey(apartmentid, params);

  const queryFn: QueryFunction<
    AsyncReturnType<typeof readUsersUserGroupsApartmentIdGet>
  > = () => readUsersUserGroupsApartmentIdGet(apartmentid, params);

  const query = useQuery<
    AsyncReturnType<typeof readUsersUserGroupsApartmentIdGet>,
    TError,
    TData
  >(queryKey, queryFn, { enabled: !!apartmentid, ...queryOptions });

  return {
    queryKey,
    ...query,
  };
};
